name: .NET Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore template/backend/Ambev.DeveloperEvaluation.sln

      - name: Build
        run: dotnet build template/backend/Ambev.DeveloperEvaluation.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test template/backend/Ambev.DeveloperEvaluation.sln --configuration Release --no-build
